apiVersion: v1
kind: Secret
metadata:
  name: blob-creds
type: Opaque
data:
  AZURE_STORAGE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXN0b3JhZ2VhY2MyNTtBY2NvdW50S2V5PU0rVFV0eGxVREpnTFg1Um1TcEdOYkhPSEZWWkJIVzhVYks2NnJ4RUNBMExybU1YMHdKMGtnSjh1SldUVERkYWFJanlIYVZ1MVVSSnArQVN0WXlrRHVnPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  AZURE_STORAGE_CONTAINER_NAME: dGVzdGNvbnRhaW5lcg==